server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      defecto:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
    instances:
      items:
        baseConfig: defecto
  timelimiter:
    configs:
      defecto:
        timeoutDuration: 2s
    instances:
      items:
        baseConfig: defecto
