apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
#  storageClassName: ""
  accessModes:
    - ReadWriteOnce
#    - ReadWriteMany
#  csi:
#    driver: efs.csi.aws.com
#    volumeHandle: fs-038e7cc1e889ba6a4
  hostPath:
    path: /var/lib/postgresql/data
    type: DirectoryOrCreate