spring:
  datasource:
    url: jdbc:mysql://mysql:3306/db_springboot_cloud
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: debug